# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
#
title: EventNetUSA
description:
url: http://www.eventnetusa.com

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: dist
# exclude: ['assets']

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: EvenNetUSA
  email:
  uri:
  bio:
  twitter:
  github:

types:
  - vehicle tour
  - grand opening
  - pr event
  - pr stunt
  - popup shop
  - insurance activation
  - retail
  - street team

collections:
  work:
    output: true
    permalink: /work/:slug/

defaults:
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      class: "home"
  -
    scope:
      path: "about.html"
    values:
      layout: "default"
      class: "about"
      permalink: "/about/"
  -
    scope:
      path: "work.html"
    values:
      layout: "default"
      class: "work"
      permalink: "/work/"
  -
    scope:
      path: "careers.html"
    values:
      layout: "default"
      class: "careers"
      permalink: "/careers/"
  -
    scope:
      path: "contact.html"
    values:
      layout: "default"
      class: "contact"
      permalink: "/contact/"
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: "casestudy"
      class: "casestudy"
      _comments:
        slug: used to create the link
        hero_image_path: image should be at least 2000px wide
        single_image_path: image should be at least 1000px wide
        video_id: a youtube video ID
        video_block: a youtube video ID
        related_client_logos: add up to five logos
        logo_image_height: use a percentage to adjust the height of a logo so it matches others
        double_image_block: these images must be square
        image_1_path: these images must be square
        image_2_path: these images must be square
        logo_image_path: upload an SVG or image with transparency
        media_section: use one or more media sections to create custom layouts
        sidebar_text_markdown: (optional)
        cta: (optional)
        subheadline: (optional)


# -
#   scope:
#     path: "blog.html"
#   values:
#     layout: "default"
#     class: "blog"
#     permalink: "/blog/"
# -
#   scope:
#     path: ""
#     type: "posts"
#   values:
#     layout: "default"
#     class: "blog"


# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
permalink: none
paginate: 10
paginate_path: 'page:num'
excerpt_separator: ''

# Markdown library and options
# markdown: redcarpet
# redcarpet:
#   extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
#               'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
# highlighter: rouge

# Extending Jekyll
gems:
  # - jekyll-feed
  # - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
