# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
#
title: EventNetUSA
description: Turnkey brand event production & management. Bringing ideas to life for marketers and agencies since 1976.
url: http://www.eventnetusa.com

# CloudCannon uses these:
source: src
destination: dist
exclude:

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: EvenNetUSA
  email:
  uri:
  bio:
  twitter:
  github:

types:
  - vehicle tour
  - pr event
  - popup shop
  - insurance activation
  - retail
  - street team

filters:
  - insights
  - press

categories:
  - insights
  - press

collections:
  work:
    output: true
    permalink: /work/:slug/
    _hide_content: true

defaults:
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      class: "home"
  -
    scope:
      path: "about.html"
    values:
      layout: "default"
      class: "about"
      permalink: "/about/"
  -
    scope:
      path: "work.html"
    values:
      layout: "default"
      class: "work"
      permalink: "/work/"
  -
    scope:
      path: "careers.html"
    values:
      layout: "default"
      class: "careers"
      permalink: "/careers/"
  -
    scope:
      path: "contact.html"
    values:
      layout: "default"
      class: "contact"
      permalink: "/contact/"
  -
    scope:
      path: ""
      type: "work"
    values:
      layout: "casestudy"
      class: "casestudy"
      _comments:
        slug: Used to create the link
        single_image_path: Image should be at least 1000px wide
        video_id: A youtube video ID
        video_block: A youtube video ID
        related_client_logos: Add up to five logos
        logo_image_height: When logo is too tall, use a percentage to decrease the height
        double_image_block: These images must be square
        image_1_path: These images must be square
        image_2_path: These images must be square
        logo_image_path: Upload an SVG or image with transparency
        content_section: Use one or more media sections to create custom layouts
        sidebar_text_markdown: (optional)
        cta: (optional)
        subheadline: (optional)
        hover_text: Shown on thumbnail hovers
        hero_image_path: Ideally 1950x750px (2.6 aspect ratio rectangle )
        thumbnail_image_path: Ideally 800x571px (1.4 aspect ratio rectangle)
  -
    scope:
      path: "blog.html"
    values:
      layout: "default"
      class: "blog"
      permalink: "/blog/"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog_item"
      class: "post"
     # _hide_content: true
      _comments:
        content_section: "NOTE: add all post content here!"
        hero_image_path: Ideally 1950x750px (2.6 aspect ratio rectangle )
        thumbnail_image_path: Ideally 800x571px (1.4 aspect ratio rectangle)
        filter: "This is the category"
      # permalink: "/blog/:slug"
  -
    scope:
      path: "cms.md"
    values:
      layout: "cms"
      permalink: "/cms/"
      _hide_content: true


# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
permalink: "/blog/:slug/"
paginate: 10
paginate_path: 'page:num'
excerpt_separator: ''

# Markdown library and options
# markdown: redcarpet
# redcarpet:
#   extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
#               'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
# highlighter: rouge

# Extending Jekyll
gems:
  # - jekyll-feed
  # - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
